config/routes.rb
Rails.application.routes.draw do


  scope "(:locale)", locale: /en|bn/ do
    root 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "registrations"}

    resources :users do
      member do
        get :orders
      end
    end
    resources :orders do
      resources :comments
    end
  #get 'accounts/index'

  resources "contacts", only: [:new, :create]
  get 'contacts/new'
  get 'contacts/create'
  get 'faq/index'
    get 'useraccounts/index'



 end
  match '/contacts', to: 'contacts#new', via: 'get'
  end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :order
	belongs_to :user

	validates :content, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New Messge from EasyGetShop Contact Form",
      :to => "mahmud.tarique@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :comments
	validates :user_id, presence: true
	validates_presence_of :body, presence: true, length: { minimum: 10, maximum: 1000  }
	#after_create { Notifier.order_created(self).deliver }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
          #:confirmable
  #include DeviseTokenAuth::Concerns::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  #after_create { Notifier.welcome_email(self).deliver }
  validates_presence_of :name, :email, :address, :phone, :fb_id


  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include DeviseTokenAuth::Concerns::SetUserByToken
	#protect_from_forgery with: :null_session
  #protect_from_forgery with: :exception
  protect_from_forgery 
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_filter :set_locale
  #include Recaptcha::Verify
  #config.i18n.default_locale = :en
 
private

	def set_locale	
		I18n.locale = params[:locale] || I18n.default_locale
    	#Rails.application.routes.default_url_options[:locale]= I18n.locale 
	end

	def default_url_options 
		{ locale: I18n.locale }
	end

  protected

  def json_request?
    request.format.json?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!



  def create
    @order = Order.find_by_id(params[:order_id])
    @comment = @order.comments.create(comments_params)
    @comment.user_id = current_user.id

   # CommentMailer.comment_created(current_user, @order.user, @comment.content).deliver

    if @comment.save 
    	redirect_to order_path(@order)
    else
    	flash.now[:danger] = "Error"
    end
    #redirect_to order_path(@order)

  end


  def destroy
  	@order = Order.find(params[:order_id])
    @comment = @order.comments.find(params[:id])
    @comment.destroy
    redirect_to order_path(@order)
end

private

def comments_params
	params.require(:comment).permit(:content, :user_id, :order_id)
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	    @contact = Contact.new

  end

  def create
  	@contact = Contact.new(params[:contact])
    @contact.request = request
    if verify_recaptcha(model: @contact) && @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end

  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  #	if user_signed_in?
  #		redirect_to orders_path

  #	else
  #	redirect_to new_user_session_path 
  	
  #	end

 end

  def profile

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders 
    if current_user.adminuser == true
      @orders = Order.all 
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.build(order_params) #Order.new(order_params)current_user.microposts.build(micropost_params)

    respond_to do |format|
      if @order.save
        p  current_user
        #OrderMailer.order_created(current_user.email).deliver
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        puts "Mail not sent "
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:body, :status, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
#skip_before_filter :verify_authenticity_token, :only => :create
	private 

	def sign_up_params
		params.require(:user).permit(:name, :email, :phone, :address, :fb_id, :password, :password_confirmation )
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :phone, :address, :fb_id, :password, :password_confirmation, :current_password)
	end

end

app/controllers/useraccounts_controller.rb
class UseraccountsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/useraccounts_helper.rb
module UseraccountsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="column">
    <p class="text-sm">Need support? Call <span class="text-primary">+8801914221142</span></p>
    <div class="social-bar text-center space-bottom">
      <a href="" class="sb-skype" data-toggle="tooltip" data-placement="top" title="Skype">
        <i class="socicon-skype"></i>
      </a>
      <a href="" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
        <i class="socicon-facebook"></i>
      </a>
      <a href="" class="sb-google-plus" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google+">
        <i class="socicon-googleplus"></i>
      </a>
      <a href="" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="Twitter">
        <i class="socicon-twitter"></i>
      </a>
      <a href="" class="sb-instagram" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
        <i class="socicon-instagram"></i>
      </a>
    </div><!-- .social-bar -->
    <p class="copyright">&copy; 2017. Made with <i class="text-danger material-icons favorite"></i> by EasyGetShop.</p>
  </div><!-- .column -->
  <div class="column">
    <h3 class="widget-title">
      Subscription
      <small>To receive latest offers and discounts from the shop.</small>
    </h3>
    <form action="http://rokaux.us12.list-manage.com/subscribe/post?u=c7103e2c981361a6639545bd5&amp;id=1194bb7544" method="post" target="_blank" class="subscribe-form" novalidate>
      <input type="email" class="form-control" name="EMAIL" placeholder="Your e-mail">
      <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c7103e2c981361a6639545bd5_1194bb7544" tabindex="-1" value=""></div>
      <button type="submit"><i class="material-icons send"></i></button>
    </form>
  </div><!-- .column -->
  <div class="column">
    <h3 class="widget-title">
      Payment Methods
      <small>We support one of the following payment methods.</small>
    </h3>
    <div class="cards"><!--<img src="img/cards.png" alt="Cards">-->
      <%= image_tag('cards.png', alt: "Cards")%>
    </div>

    <!-- Scroll To Top Button -->
    <div class="scroll-to-top-btn"><i class="material-icons trending_flat"></i></div>
  </div><!-- .column -->
</footer><!-- .footer -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <% if user_signed_in? %>
        <%= link_to image_tag("logo.png", alt: "logo"), orders_path, id: "logo",  class: 'navbar-brand'%>
    <% else %>
        <%= link_to image_tag("logo.png", alt: "logo"), root_path, id: "logo",  class: 'navbar-brand'%>
    <% end %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", orders_path%></li>
            <% if user_signed_in? %>
            <li><%= link_to "Your Orders", orders_path(current_user) %></li>
            <li><%= link_to "Create New Order", new_order_path%></li>
            <li><%= link_to "Edit My Account", edit_user_registration_path%></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete'%></li>
            <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Contact Us", contacts_new_path%></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_navbar.html.erb
<!-- Page Wrapper -->


  <!-- Navbar -->
  <!-- Remove ".navbar-sticky" class to make navigation bar scrollable with the page. -->
  <header class="navbar navbar-sticky">

    <!-- Site Logo -->
    <%= link_to "<span>[</span> EasyGet <span class='text-gray'/></span>SHOP <span>]</span>".html_safe, root_path, class: "site-logo visible-desktop" %>
    <!-- site-logo.visible-desktop -->

    <!-- Language Switcher -->
    <div class="lang-switcher pull-right">
      ভাষা নির্বাচন করুন: <%= link_to_unless_current "English", locale: "en"%> |
      <%= link_to_unless_current "বাংলা", locale: "bn"%>
    </div><!-- .lang-switcher -->

    <!-- Main Navigation -->
    <!-- Control the position of navigation via modifier classes: "text-left, text-center, text-right" -->
    <nav class="main-navigation text-center">
      <ul class="menu">
        <li><%= link_to "Home", root_path, class: "current-menu-item"%></li>

        <% if user_signed_in? %>
            <li class="menu-item-has-children"><%= link_to "Orders", orders_path, class: "menu-item-has-children"%>
              <ul class="sub-menu">
                <li><%= link_to "Create New Order", new_order_path %></li>
                <li><%= link_to "My Orders", orders_path%></li>
                <li><%= link_to "Recieved Orders"%></li>
                <li><%= link_to "Current Orders" %></li>
              </ul>
            </li>
        <li><%= link_to "Create a New Order", new_order_path%></li>
        <li><%= link_to "My Account", "#", class: "menu-item-has-children"%>
          <ul class="sub-menu">
            <li><%= link_to "Edit Account", edit_user_registration_path%></li>
            <li><%= link_to "My Account", useraccounts_index_path%></li>
          </ul>
        </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete'%></li>
            <%else%>

            <li><%= link_to "Create a New Order", new_user_registration_path%></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <!--<li><%#= link_to "Sign Up", new_user_registration_path %></li>-->
            <%end%>
        <li><%= link_to "Contact", new_contact_path%></li>
        <li><%= link_to "FAQ", faq_index_path%></li>
      </ul><!-- .menu -->
    </nav><!-- .main-navigation -->


  </header>

app/views/layouts/_notice.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_preloader.html.erb
<!-- Page Pre-Loader -->
<div class="page-preloader">
  <div class="preloader">
    <!--
        <img src="img/preloader.gif" alt="Preloader">
    -->
    <%= image_tag('preloader.gif')%>

  </div>
</div><!-- .page-preloader -->

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyGetShop</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="EasyGetShop">
    <meta name="author" content="Gazi Tarique Mahmud">
   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
     <%= csrf_meta_tags %>
  
  </head>

  <body class="page-preloading">
    <%= render 'layouts/preloader'%>
      <div class="page-wrapper">
        <%= render 'layouts/navbar'%>
        <%= render 'layouts/notice' %>

        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>